// src/vue/App.vue
<script setup lang="ts">
import { computed } from 'vue';
import { provideSession, useSession } from './sessionStore';
import AuthScreen from './components/AuthScreen.vue';
import EmailSetupScreen from './components/EmailSetupScreen.vue';
import TerminalApp from './components/TerminalApp.vue';

provideSession();

const { session, isActingAsVendor } = useSession();

const currentView = computed(() => {
  if (!session.currentUser) return 'auth';
  if (session.currentUser.role === 'guest' || isActingAsVendor()) return 'terminal';
  const user = session.users.find((u) => u.username === session.currentUser?.username);
  if (user && !user.email) return 'email';
  return 'terminal';
});

const handleEmailComplete = () => {
  // Session already updated by updateEmail, view recalculates automatically
};
</script>

<template>
  <div class="min-h-screen bg-[#0d0118]">
    <AuthScreen v-if="currentView === 'auth'" />
    <EmailSetupScreen v-else-if="currentView === 'email'" @complete="handleEmailComplete" />
    <TerminalApp v-else />
  </div>
</template>

// src/svelte/App.svelte
<script lang="ts">
  import { createSession, useSession } from './sessionStore';
  import AuthScreen from './components/AuthScreen.svelte';
  import EmailSetupScreen from './components/EmailSetupScreen.svelte';
  import TerminalApp from './components/TerminalApp.svelte';

  createSession();

  const { session, isActingAsVendor } = useSession();

  const currentView = $derived(() => {
    if (!session.currentUser) return 'auth';
    if (session.currentUser.role === 'guest' || isActingAsVendor()) return 'terminal';
    const user = session.users.find((u) => u.username === session.currentUser?.username);
    if (user && !user.email) return 'email';
    return 'terminal';
  });
</script>

<div class="min-h-screen bg-[#0d0118]">
  {#if currentView() === 'auth'}
    <AuthScreen />
  {:else if currentView() === 'email'}
    <EmailSetupScreen oncomplete={() => {}} />
  {:else}
    <TerminalApp />
  {/if}
</div>
