// src/svelte/App.svelte
<script lang="ts">
  import { createSession, useSession } from './sessionStore';
  import AuthScreen from './components/AuthScreen.svelte';
  import EmailSetupScreen from './components/EmailSetupScreen.svelte';
  import TerminalApp from './components/TerminalApp.svelte';

  createSession();

  const { session, isActingAsVendor } = useSession();

  const currentView = $derived(() => {
    if (!session.currentUser) return 'auth';
    if (session.currentUser.role === 'guest' || isActingAsVendor()) return 'terminal';
    const user = session.users.find((u) => u.username === session.currentUser?.username);
    if (user && !user.email) return 'email';
    return 'terminal';
  });
</script>

<div class="min-h-screen bg-[#0d0118]">
  {#if currentView() === 'auth'}
    <AuthScreen />
  {:else if currentView() === 'email'}
    <EmailSetupScreen oncomplete={() => {}} />
  {:else}
    <TerminalApp />
  {/if}
</div>

// src/react/App.tsx
import { SessionProvider, useSession } from './sessionStore';
import { TerminalApp } from './components/TerminalApp';
import { AuthScreen } from './components/AuthScreen';
import { EmailSetupScreen } from './components/EmailSetupScreen';

function AppContent() {
  const { session } = useSession();

  if (!session.currentUser) {
    return <AuthScreen />;
  }

  // Guest users and admin skip email requirement
  const isGuest = session.currentUser.role === 'guest';
  const isActingAsVendor = session.originalAdmin !== null;

  if (!isGuest && !isActingAsVendor) {
    const currentUserData = session.users.find(
      u => u.username.toLowerCase() === session.currentUser!.username.toLowerCase()
    );
    if (!currentUserData?.email) {
      return <EmailSetupScreen onComplete={() => {}} />;
    }
  }

  return <TerminalApp />;
}

export default function App() {
  return (
    <SessionProvider>
      <div className="min-h-screen bg-[#0d0118]">
        <AppContent />
      </div>
    </SessionProvider>
  );
}
